### ISSUE TITLE
Using SliderModel_() causes a crash

### ISSUE THREAD

**Issue by Shanazar1** [worldsnas/slider#2]
```kotlin
class MyController(private val onAdClick: (String) -> Unit): EpoxyController() {
    private var ads = emptyList<Ad>()
    fun submit(ads: List<Ad>) {
        this.ads = ads
        requestModelBuild()
    }
    override fun buildModels() {
        val models = ads.map { AdModel(it, onAdClick).id("ad${it.id}") }
        SliderModel_().id("ads").models(models).addTo(this) // here
    }
}
data class AdModel(val ad: Ad, val onAdClick: (String) -> Unit): ViewBindingKotlinModel<ViewAdBinding>(R.layout.view_ad) {
    override fun ViewAdBinding.bind() {
        Glide.with(imageView).load(ad.thumbnailUrl).into(imageView)
        imageView.setOnClickListener { onAdClick(ad.url) }
    }
}
```
> java.lang.NullPointerException
>         at com.shanazar.myproject.MyFragment$onViewCreated$5$invokeSuspend$$inlined$collect$1.emit(Collect.kt:145)
>         at kotlinx.coroutines.flow.StateFlowImpl.collect(StateFlow.kt:348)
>         at kotlinx.coroutines.flow.ReadonlyStateFlow.collect(Unknown Source:2)
>         at com.shanazar.myproject.MyFragment$onViewCreated$5.invokeSuspend(MyFragment.kt:152)

ViewBindingKotlinModel.kt:
https://github.com/airbnb/epoxy/blob/master/kotlinsample/src/main/java/com/airbnb/epoxy/kotlinsample/helpers/ViewBindingKotlinModel.kt

**Comment by Shanazar1** [comment]
Works now, my mistake
